services:
  app:
    build:
      context: .
    container_name: python_scraper
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0
    container_name: ktncm_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/:ro