name: ci

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          
      - name: Run tests with pytest
        run: pytest --cov=source --cov-report=xml

      - name: Store unit test coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: error

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  push-to-google:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker to Google Artifact Registry
      run: |
        gcloud auth configure-docker europe-west6-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build --build-arg DB_CERTIFICATE_B64="${{ secrets.DB_CERTIFICATE_B64 }}" \
                   -t europe-west6-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ktncm-docker/python-scraper:v1 .

    - name: Push Docker image
      run: |
        docker push europe-west6-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ktncm-docker/python-scraper:v1